In [1]:
import numpy as np

In [2]:
a = np.arange(5)

In [3]:
a

array([0, 1, 2, 3, 4])

In [4]:
np.concatenate((a,a))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [5]:
aa = np.arange(6).reshape(2,3)

In [7]:
np.concatenate((aa,aa))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [10]:
np.concatenate((aa,aa), axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [14]:
np.append(a,3)

array([0, 1, 2, 3, 4, 3])

In [15]:
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
np.append(aa,3)

array([0, 1, 2, 3, 4, 5, 3])

In [17]:
np.append(aa,aa)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [20]:
np.hstack((aa,aa))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [21]:
np.vstack((aa,aa))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [22]:
np.dstack((aa,aa))

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]]])

In [23]:
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
np.stack((aa,aa), axis=0)

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [27]:
np.stack((aa,aa), axis=0).shape

(2, 2, 3)

In [28]:
np.column_stack((aa,aa))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [29]:
np.row_stack((aa,aa))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [30]:
np.r_[aa,aa]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [31]:
np.c_[aa,aa]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [32]:
aaa = np.arange(24).reshape(4,6)

In [33]:
aaa

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [35]:
np.vsplit(aaa,(2,2))

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([], shape=(0, 6), dtype=int32),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [36]:
np.vsplit(aaa,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [39]:
np.split(aaa,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]