In [47]:
import seaborn as sns

In [48]:
tips = sns.load_dataset('tips')

In [49]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [10]:
type(tips['sex'])

pandas.core.series.Series

In [11]:
tips.tip + 1

0      2.01
1      2.66
2      4.50
3      4.31
4      4.61
       ... 
239    6.92
240    3.00
241    3.00
242    2.75
243    4.00
Name: tip, Length: 244, dtype: float64

In [12]:
1,None,2

(1, None, 2)

In [14]:
import numpy as np

In [24]:
#mask array
x = np.ma.array([1,2,3,], mask=[True, False, False])

In [25]:
x

masked_array(data=[--, 2, 3],
             mask=[ True, False, False],
       fill_value=999999)

In [26]:
x.count()

2

In [27]:
len(x)

3

In [28]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [29]:
tips.sex.describe()

count      244
unique       2
top       Male
freq       157
Name: sex, dtype: object

In [60]:
tips.tip[0] = None #(None -> NaN)

C:\Users\USER\AppData\Local\Temp\ipykernel_9164\2208186701.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tips.tip[0] = None #(None -> NaN)


In [61]:
tips.tip[0]== None #descripter 때문에 false가 뜸

False

In [70]:
tips.tip.sum(skipna=True) #pandas 만이 skipna=True를 지원, float 또 대충 계산했구나

730.5699999999999

In [71]:
tips.tip

0       NaN
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [72]:
a = np.arange(24).reshape(4,6)

In [73]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [74]:
x = np.arange(24)

In [81]:
x.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [87]:
x.reshape(4,2,-3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [114]:
x = np.arange(24)

In [115]:
x.resize(3,10)

In [116]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  0,  0,  0,  0,  0]])

In [101]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  0,  0,  0,  0,  0])

In [102]:
# copy: 얕은 복사는 1차원 배열에서만 가능
# 2차에서는 얕은 복사 불가. copy를 써도 수정될 시 원래 datafram도 수정됨.

In [103]:
import copy
xx =[[1,2],[3,4]]
yy = copy.deepcopy(xx)
yy[1][1] = 100
xx

[[1, 2], [3, 4]]

In [117]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  0,  0,  0,  0,  0]])

In [118]:
y = x.flatten()

In [119]:
x[0,0] = 100

In [122]:
y.ravel() #라벨 = 볼레로 = 뷰

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  0,  0,  0,  0,  0])