# data import

In [1]:
import pandas as pd

In [2]:
rating = pd.read_csv('C:/Users/USER/Desktop/ml-100k/u.data', delimiter='\t', header=None, 
                   names=['user id','item id','rating','timestamp']) # sep

In [3]:
rating.rename({'item id':'movie id'}, axis=1, inplace=True)

In [4]:
movie id | movie title | release date | video release date |
              IMDb URL | unknown | Action | Adventure | Animation |
              Children's | Comedy | Crime | Documentary | Drama | Fantasy |
              Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi |
              Thriller | War | Western |

SyntaxError: invalid syntax (1561714889.py, line 1)

In [4]:
movie = pd.read_csv('C:/Users/USER/Desktop/ml-100k/u.item', sep='|', encoding='latin1', header=None)

In [5]:
movie.rename(columns={0:'movie id',1:'movie title', 2:'release date'}, inplace=True)

In [6]:
!pip install -U xlwt

In [7]:
movie.to_excel('movie.xls', index=False)

C:\Users\USER\AppData\Local\Temp\ipykernel_26184\3697643372.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  movie.to_excel('movie.xls', index=False)


In [8]:
movie

movie id                                movie title release date   3  \
0            1                           Toy Story (1995)  01-Jan-1995 NaN   
1            2                           GoldenEye (1995)  01-Jan-1995 NaN   
2            3                          Four Rooms (1995)  01-Jan-1995 NaN   
3            4                          Get Shorty (1995)  01-Jan-1995 NaN   
4            5                             Copycat (1995)  01-Jan-1995 NaN   
...        ...                                        ...          ...  ..   
1677      1678                          Mat' i syn (1997)  06-Feb-1998 NaN   
1678      1679                           B. Monkey (1998)  06-Feb-1998 NaN   
1679      1680                       Sliding Doors (1998)  01-Jan-1998 NaN   
1680      1681                        You So Crazy (1994)  01-Jan-1994 NaN   
1681      1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996 NaN   

                                                      4  5  6  7  8  9  ...  \
0     http://us.imdb.com/M/title-exact?Toy%20Story%2...  0  0  0  1  1  ...   
1     http://us.imdb.com/M/title-exact?GoldenEye%20(...  0  1  1  0  0  ...   
2     http://us.imdb.com/M/title-exact?Four%20Rooms%...  0  0  0  0  0  ...   
3     http://us.imdb.com/M/title-exact?Get%20Shorty%...  0  1  0  0  0  ...   
4     http://us.imdb.com/M/title-exact?Copycat%20(1995)  0  0  0  0  0  ...   
...                                                 ... .. .. .. .. ..  ...   
1677  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...  0  0  0  0  0  ...   
1678  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...  0  0  0  0  0  ...   
1679      http://us.imdb.com/Title?Sliding+Doors+(1998)  0  0  0  0  0  ...   
1680  http://us.imdb.com/M/title-exact?You%20So%20Cr...  0  0  0  0  0  ...   
1681  http://us.imdb.com/M/title-exact?Schrei%20aus%...  0  0  0  0  0  ...   

      14  15  16  17  18  19  20  21  22  23  
0      0   0   0   0   0   0   0   0   0   0  
1      0   0   0   0   0   0   0   1   0   0  
2      0   0   0   0   0   0   0   1   0   0  
3      0   0   0   0   0   0   0   0   0   0  
4      0   0   0   0   0   0   0   1   0   0  
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  
1677   0   0   0   0   0   0   0   0   0   0  
1678   0   0   0   0   0   1   0   1   0   0  
1679   0   0   0   0   0   1   0   0   0   0  
1680   0   0   0   0   0   0   0   0   0   0  
1681   0   0   0   0   0   0   0   0   0   0  

[1682 rows x 24 columns]

In [9]:
pd.read_excel('item.xls')

FileNotFoundError: [Errno 2] No such file or directory: 'item.xls'

In [10]:
user = pd.read_csv('C:/Users/USER/Desktop/ml-100k/u.user', sep='|', header=None, names=['user id','age','gender','occupation','zip code'])

In [11]:
user

user id  age gender     occupation zip code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [12]:
rating.columns

Index(['user id', 'movie id', 'rating', 'timestamp'], dtype='object')

In [13]:
rating.merge(movie).merge(user)

user id  movie id  rating  timestamp  \
0          196       242       3  881250949   
1          196       257       2  881251577   
2          196       111       4  881251793   
3          196        25       4  881251955   
4          196       382       4  881251843   
...        ...       ...     ...        ...   
99995      873       313       5  891392177   
99996      873       326       4  891392656   
99997      873       348       3  891392577   
99998      873       358       2  891392698   
99999      873       342       4  891392698   

                                             movie title release date   3  \
0                                           Kolya (1996)  24-Jan-1997 NaN   
1                                    Men in Black (1997)  04-Jul-1997 NaN   
2                    Truth About Cats & Dogs, The (1996)  26-Apr-1996 NaN   
3                                   Birdcage, The (1996)  08-Mar-1996 NaN   
4      Adventures of Priscilla, Queen of the Desert, ...  01-Jan-1994 NaN   
...                                                  ...          ...  ..   
99995                                     Titanic (1997)  01-Jan-1997 NaN   
99996                                   G.I. Jane (1997)  01-Jan-1997 NaN   
99997                          Desperate Measures (1998)  30-Jan-1998 NaN   
99998                                       Spawn (1997)  01-Aug-1997 NaN   
99999                Man Who Knew Too Little, The (1997)  01-Jan-1997 NaN   

                                                       4  5  6  ...  18  19  \
0        http://us.imdb.com/M/title-exact?Kolya%20(1996)  0  0  ...   0   0   
1      http://us.imdb.com/M/title-exact?Men+in+Black+...  0  1  ...   0   0   
2      http://us.imdb.com/M/title-exact?Truth%20About...  0  0  ...   0   1   
3      http://us.imdb.com/M/title-exact?Birdcage,%20T...  0  0  ...   0   0   
4      http://us.imdb.com/M/title-exact?Adventures%20...  0  0  ...   0   0   
...                                                  ... .. ..  ...  ..  ..   
99995  http://us.imdb.com/M/title-exact?imdb-title-12...  0  1  ...   0   1   
99996  http://us.imdb.com/M/title-exact?G%2EI%2E+Jane...  0  1  ...   0   0   
99997  http://us.imdb.com/Title?Desperate+Measures+(1...  0  0  ...   0   0   
99998    http://us.imdb.com/M/title-exact?Spawn+(1997/I)  0  1  ...   0   0   
99999  http://us.imdb.com/M/title-exact?Man+Who+Knew+...  0  0  ...   1   0   

       20  21  22  23  age  gender     occupation  zip code  
0       0   0   0   0   49       M         writer     55105  
1       1   0   0   0   49       M         writer     55105  
2       0   0   0   0   49       M         writer     55105  
3       0   0   0   0   49       M         writer     55105  
4       0   0   0   0   49       M         writer     55105  
...    ..  ..  ..  ..  ...     ...            ...       ...  
99995   0   0   0   0   48       F  administrator     33763  
99996   0   0   1   0   48       F  administrator     33763  
99997   0   1   0   0   48       F  administrator     33763  
99998   1   1   0   0   48       F  administrator     33763  
99999   0   0   0   0   48       F  administrator     33763  

[100000 rows x 31 columns]

In [14]:
pd.to_datetime(rating.timestamp, unit='s')

0       1997-12-04 15:55:49
1       1998-04-04 19:22:22
2       1997-11-07 07:18:36
3       1997-11-27 05:02:03
4       1998-02-02 05:33:16
                ...        
99995   1997-11-22 05:10:44
99996   1997-11-17 19:39:03
99997   1997-09-20 22:49:55
99998   1997-12-17 22:52:36
99999   1997-11-19 17:13:03
Name: timestamp, Length: 100000, dtype: datetime64[ns]

# user item matrix

In [15]:
rating2 = rating[['user id', 'movie id', 'rating']]

In [16]:
rating2.pivot(index='user id', columns='movie id', values='rating')

movie id  1     2     3     4     5     6     7     8     9     10    ...  \
user id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5          4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   
940        NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   
941        5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
942        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
943        NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   

movie id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user id                                                               
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[943 rows x 1682 columns]

In [17]:
rating3 = rating2.set_index(['user id','movie id']).unstack().fillna(0)

In [18]:
rating4 = rating3.T

# similarity

In [19]:
rating5 = rating4.corr()

In [20]:
rating5[3].sort_values(ascending=False)

user id
3      1.000000
863    0.470011
616    0.469289
489    0.466023
784    0.454013
         ...   
279   -0.040018
406   -0.040046
321   -0.046283
312   -0.052013
932   -0.065909
Name: 3, Length: 943, dtype: float64

In [21]:
rating5[3].nsmallest(5)

user id
932   -0.065909
312   -0.052013
321   -0.046283
406   -0.040046
279   -0.040018
Name: 3, dtype: float64

In [22]:
rating3.to_numpy()

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [23]:
def sim_me(user_id, n=5):
    return rating5[user_id].nlargest(n+1).index[1:].values

In [24]:
sim_me(423)

array([784, 616, 100, 190, 834], dtype=int64)

In [25]:
rating33 = rating2.pivot(index='user id', columns='movie id', values='rating').fillna(0)

In [26]:
sim_me(1)

array([916, 738, 864, 457, 268], dtype=int64)

# 나와 유사한 사람들이 했지만 내가 경험하지 않은 것 찾기

In [27]:
set(rating[rating['user id'].isin(sim_me(1))]['movie id'].values)

{1,
 2,
 3,
 4,
 5,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 20,
 21,
 22,
 23,
 24,
 25,
 27,
 28,
 29,
 30,
 31,
 33,
 37,
 38,
 39,
 40,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 76,
 77,
 79,
 80,
 81,
 82,
 83,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 105,
 106,
 108,
 109,
 111,
 114,
 116,
 117,
 118,
 120,
 121,
 122,
 123,
 124,
 125,
 127,
 128,
 129,
 132,
 133,
 134,
 135,
 136,
 137,
 139,
 140,
 141,
 143,
 144,
 145,
 147,
 148,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 2

In [28]:
set(rating[rating['user id']==1]['movie id'].values)

{1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [29]:
def not_show_movie(user_id):
    return set(rating[rating['user id'].isin(sim_me(user_id))]['movie id'].values)-set(rating[rating['user id']==user_id]['movie id'].values)

In [30]:
not_show_movie(3)

{242,
 243,
 259,
 261,
 262,
 263,
 266,
 269,
 270,
 286,
 289,
 292,
 301,
 304,
 305,
 306,
 308,
 310,
 312,
 313,
 315,
 316,
 358,
 359,
 360,
 361,
 362,
 457,
 538,
 539,
 678,
 680,
 681,
 682,
 683,
 687,
 688,
 689,
 690,
 691,
 748,
 749,
 750,
 751,
 752,
 754,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 885,
 886,
 887,
 890,
 892,
 895,
 897,
 898,
 900,
 901,
 902,
 903,
 906,
 908,
 909,
 910,
 937,
 948,
 984,
 988,
 989,
 990,
 991,
 1022,
 1024,
 1025,
 1038,
 1062,
 1127,
 1234,
 1237,
 1238,
 1243,
 1265,
 1280,
 1293,
 1294,
 1296,
 1313,
 1395,
 1431,
 1434,
 1607,
 1612,
 1613,
 1678,
 1679,
 1680}

In [31]:
rating[(rating['user id']==1) | (rating['user id']==2)]

user id  movie id  rating  timestamp
202          1        61       4  878542420
305          1       189       3  888732928
333          1        33       4  878542699
334          1       160       4  875072547
478          1        20       4  887431883
...        ...       ...     ...        ...
94019        1       122       3  875241498
95677        2       302       5  888552084
96699        1       152       5  878542589
97619        2       296       3  888550871
99073        1        94       2  875072956

[334 rows x 4 columns]

In [32]:
rating['user id'].isin([1,2])

0        False
1        False
2        False
3        False
4        False
         ...  
99995    False
99996    False
99997    False
99998    False
99999    False
Name: user id, Length: 100000, dtype: bool

In [33]:
import keyword

In [34]:
keyword.kwlist < in : operator loading

SyntaxError: invalid syntax (3100608666.py, line 1)

In [112]:
def movie_show_me(user_id):
    return rating[rating['user id']==user_id]['movie id'].values

In [113]:
movie_show_me(3)

array([335, 245, 337, 343, 323, 331, 294, 332, 328, 334, 350, 341, 318,
       300, 345, 299, 324, 348, 351, 330, 327, 307, 272, 354, 264, 349,
       321, 260, 268, 288, 355, 320, 258, 339, 342, 303, 329, 317, 181,
       338, 302, 322, 352, 271, 333, 344, 326, 319, 325, 347, 336, 353,
       340, 346], dtype=int64)

In [35]:
1 in [1,2,3]

True