In [1]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
dtype, shape

In [3]:
a = np.array([[1,1,1,],[1,1,1]])

In [4]:
a.shape

(2, 3)

In [5]:
a.dtype

dtype('int32')

In [6]:
a = np.array([[1,1,1,],[1,1,1]], dtype=np.float64)

In [7]:
a.shape

(2, 3)

In [8]:
a.dtype

dtype('float64')

In [9]:
tf.constant([[1,1,1,],[1,1,1]], dtype=np.float64)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [10]:
b = torch.ones((3,4))

In [11]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
b.shape

torch.Size([3, 4])

In [13]:
b.dtype

torch.float32

In [20]:
tf.ones((2,3,4), dtype=tf.int32)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])>

In [23]:
torch.ones((2,3,4), dtype= torch.int32)

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)

In [34]:
a = np.array([1,2,'3'])

In [35]:
a.dtype

dtype('<U11')

In [40]:
b = tf.constant([1,2,'3'])

ValueError: Can't convert Python sequence with mixed types to Tensor.

In [39]:
c = torch.Tensor([1,2,'3'])

TypeError: must be real number, not str