# Homogeneous

In [21]:
import array #data 구조, 수학적 컨셉 없음

In [2]:
a = array.array('i', [1,2,3])

In [3]:
a

array('i', [1, 2, 3])

In [5]:
a + a #data 컨셉이지만, 수학적 컨셉은 없음

array('i', [1, 2, 3, 1, 2, 3])

In [7]:
[1,2,3] + [4,5,6] #vectorized

TypeError: can't multiply sequence by non-int of type 'list'

In [8]:
#numpy: 숫자를 다루기 위한 숫자 컨셉 - homogeneous 컨셉, C지원 -> vectorized 지원

In [9]:
def test_sum(a,b):
    return a+b

In [11]:
test_sum([1,2,3],[4,5,6])

[1, 2, 3, 4, 5, 6]

In [22]:
import numpy as np #수학적 컨셉 지원

In [18]:
@np.vectorize #decorator
def test_sum(a,b):
    return a+b

In [19]:
test_sum([1,2,3],[4,5,6])

array([5, 7, 9])

In [23]:
#vector: 1차 matrix: 2차, tensor: 3차 이상

# numpy
: mdarray (tensor -> linear algebra)

: vectorize (gpu (x))

: expert (general)

# Tensor

: numpy 기반, but gpu 지원

: neural network를 위한 함수 지원

In [24]:
a = np.array([1,2,3])

In [49]:
a = np.zeros((3,3))

In [50]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
type(a)

numpy.ndarray

In [53]:
np.ndarray((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 2.33646845e-307]])

In [54]:
a = np.eye(3)

In [57]:
a #__repr__

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
print(a)  #__str__

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
import numpy as np
import torch #데이터에 괄호
import tensorflow as tf

In [66]:
c = tf.constant([1,2,3])

In [73]:
c #__repr

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [74]:
print(c)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [75]:
#factory methon

In [76]:
type(c)

tensorflow.python.framework.ops.EagerTensor

In [77]:
b = torch.Tensor([1,2,3])

In [78]:
type(b)

torch.Tensor

In [79]:
torch.ones(1,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [80]:
tf.ones((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [81]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
np.ndarray((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 2.33646845e-307]])

In [85]:
a = np.arange(24).reshape(2,3,4,1)

In [86]:
a

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]],


       [[[12],
         [13],
         [14],
         [15]],

        [[16],
         [17],
         [18],
         [19]],

        [[20],
         [21],
         [22],
         [23]]]])

In [87]:
x = tf.keras.datasets.mnist.load_data()

In [88]:
x

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [92]:
len(x)

2

In [93]:
x = tf.keras.datasets.imdb.load_data()

17464789/17464789 [==============================] - 6s 0us/step


In [94]:
x

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [95]:
len(x)

2

In [96]:
(a,b),(c,d) = x

In [97]:
a

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [99]:
a.shape

(25000,)

# numpy
: mdarray (tensor -> linear algebra)

: vectorize (gpu (x))

: expert (general)

In [100]:
a = np.arange(24).reshape(4,6)

In [101]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [105]:
a[1,1:]

array([ 7,  8,  9, 10, 11])

In [106]:
a[1][1]

7

In [110]:
a[[2,1]] #pensing indexing

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11]])

In [111]:
a[[1,1],[3,2]]

array([9, 8])

In [112]:
import numpy as np

In [113]:
a = np.arange(24).reshape(2,3,4)

In [114]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [115]:
a[:,1,1:3]

array([[ 5,  6],
       [17, 18]])

In [121]:
a.sum(axis=2) #축

array([[ 6, 22, 38],
       [54, 70, 86]])