In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(4,6)

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a.dtype

dtype('int32')

In [5]:
a.itemsize

4

In [6]:
a.strides

(24, 4)

In [11]:
a.shape

(4, 6)

In [12]:
a.sum(axis=0) #한 줄로 reduction (열 기준) a.shape에서 4,6이므로, 4를 없애버린다는 의미

array([36, 40, 44, 48, 52, 56])

In [13]:
a.sum(axis=1) #한 줄로 reduction (행 기준)

array([ 15,  51,  87, 123])

In [14]:
a = np.arange(24).reshape(3,2,4)

In [15]:
a.sum(axis=None)

276